# Generated by Django 6.0 on 2026-01-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tubing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Тюбинг номер')),
                ('status', models.CharField(choices=[('available', 'Бос'), ('busy', 'Бос емес'), ('broken', 'Жөндеуде')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тюбинг',
                'verbose_name_plural': 'Тюбинги',
            },
        ),
    ]
