# Generated by Django 5.2.7 on 2026-01-04 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100, verbose_name='Имя гостя')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена')], default='active', max_length=20, verbose_name='Статус')),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговая сумма')),
                ('tubing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentals.tubing', verbose_name='Тюбинг')),
            ],
            options={
                'verbose_name': 'Сессия аренды',
                'verbose_name_plural': 'Сессии аренды',
                'ordering': ['-start_time'],
            },
        ),
    ]
