# Generated by Django 6.0 on 2026-01-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rentalsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalsession',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер телефона'),
        ),
    ]
